# Generated by Django 2.2.17 on 2020-12-01 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=8)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='cities.City')),
            ],
            options={
                'verbose_name': 'weather series',
                'verbose_name_plural': 'weather series',
            },
        ),
    ]
